
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 1008005
 */
public class logininter extends javax.swing.JFrame {

    /**
     * Creates new form telalo
     */
    public logininter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        cadastro = new javax.swing.JToggleButton();
        consulta = new javax.swing.JToggleButton();
        campouser = new javax.swing.JTextField();
        senhafield = new javax.swing.JTextField();
        alterar = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        atualizar = new javax.swing.JToggleButton();

        jLabel5.setText("Senha");

        jToggleButton2.setText("jToggleButton2");

        jToggleButton3.setText("jToggleButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadastro.setForeground(new java.awt.Color(153, 255, 0));
        cadastro.setText("cadastrar");
        cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroActionPerformed(evt);
            }
        });
        getContentPane().add(cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        consulta.setForeground(new java.awt.Color(153, 255, 0));
        consulta.setText("consulta");
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
            }
        });
        getContentPane().add(consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 80, -1));

        campouser.setForeground(new java.awt.Color(153, 255, 0));
        campouser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campouserActionPerformed(evt);
            }
        });
        getContentPane().add(campouser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 81, -1));

        senhafield.setForeground(new java.awt.Color(153, 255, 0));
        senhafield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhafieldActionPerformed(evt);
            }
        });
        getContentPane().add(senhafield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 81, -1));

        alterar.setForeground(new java.awt.Color(153, 255, 0));
        alterar.setText("delet");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });
        getContentPane().add(alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 80, -1));

        jLabel1.setForeground(new java.awt.Color(153, 255, 0));
        jLabel1.setText("Senha");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jLabel2.setForeground(new java.awt.Color(102, 255, 51));
        jLabel2.setText("Login");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setForeground(new java.awt.Color(51, 0, 255));
        jLabel3.setText("Login");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        atualizar.setForeground(new java.awt.Color(153, 255, 0));
        atualizar.setText("atualizar");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });
        getContentPane().add(atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
    int id;
    try {
        id = Integer.parseInt(campouser.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "ID inválido. Digite um número.");
        return;
    }

    maiessequeele usuarioDAO = new maiessequeele();
    usuarioDAO.deletar(id);

    JOptionPane.showMessageDialog(null, "Usuário deletado com sucesso!");
    }//GEN-LAST:event_alterarActionPerformed

    private void cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroActionPerformed
                     String login = campouser.getText();

                String senha;

                try {

                    senha = (senhafield.getText());

                } catch (NumberFormatException ex) {

                    JOptionPane.showMessageDialog(null, "Senha deve ser um número.");

                    return;

                }
 
                Usuario usuario = new Usuario();

                usuario.setLogin(login);

                usuario.setSenha(senha);

                maiessequeele usuarioDAO = new maiessequeele();

                usuarioDAO.inserir(usuario);
 
                

          System.out.println("Cadastro realizado1!");
          
    }//GEN-LAST:event_cadastroActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
try {
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID do usuário que deseja atualizar:"));
        String login = campouser.getText();
        String senha = senhafield.getText();

        Usuario usuario = new Usuario();
        usuario.setId(id);
        usuario.setLogin(login);
        usuario.setSenha(senha);

        maiessequeele usuarioDAO = new maiessequeele();
        usuarioDAO.atualizar(usuario);

        JOptionPane.showMessageDialog(null, "Usuário atualizado com sucesso!");
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "ID inválido.");
    }
    }//GEN-LAST:event_atualizarActionPerformed

    private void campouserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campouserActionPerformed
    }//GEN-LAST:event_campouserActionPerformed

    private void senhafieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhafieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhafieldActionPerformed

    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed
        maiessequeele usuarioDAO = new maiessequeele();
    java.util.List<Usuario> usuarios = usuarioDAO.listar();

    if (usuarios.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Nenhum usuário cadastrado.");
    } else {
        StringBuilder sb = new StringBuilder();
        for (Usuario u : usuarios) {
            sb.append("ID: ").append(u.getId())
              .append(" | Login: ").append(u.getLogin())
              .append(" | Senha: ").append(u.getSenha())
              .append("\n");
        }
        JOptionPane.showMessageDialog(null, sb.toString(), "Usuários Cadastrados", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_consultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logininter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logininter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logininter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logininter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logininter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton alterar;
    private javax.swing.JToggleButton atualizar;
    private javax.swing.JToggleButton cadastro;
    private javax.swing.JTextField campouser;
    private javax.swing.JToggleButton consulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JTextField senhafield;
    // End of variables declaration//GEN-END:variables
}
